Viewframe update
open2c/cooltools pull request #265
Opened 2021-08-31 20:50 UTC by agalitsyna

Cooltools transfer to bioframe.viewframe
Key tasks/issues resolved: 
- 1-5 from https://github.com/open2c/cooltools/issues/262
- https://github.com/open2c/cooltools/issues/255
- https://github.com/open2c/cooltools/issues/254

2021-09-02 15:51 UTC, sergpolly requested changes
This looks great ! Should be ready to merge after we fix maybe a couple of tiny items:
1. `RuntimeError`  -> `ValueError` in a couple of places
2. remove some comments related to the issues with `regions, regions2` not being unique for trans and some asymmetric cases
3. resolve the debate regarding coverage - i.e. do we do `cov` or `cov/2` ?

We cannot do much with `black`, can we ? I feel like we ran `black` on the entire codebase before, but some weird formatting changes are still creeping in. I don't understand it fully. Maybe we could agree on doing `black` as separate PRs every now and then, to make the changes looks smaller ? Also , any chance we could have slightly different `black` parameters - so that we keep re-`blacking` over and over ?

2021-09-02 15:51 UTC, sergpolly commented on cooltools/dotfinder.py
> +                "count",
sometime `black` does strange things - like this one ...
I hope, at least , that it stays consistent from run to run, from version to version

2021-09-02 15:51 UTC, sergpolly commented on tests/test_compartments_saddle.py
> +        ["call-compartments", "--contact-type", "trans", "-o", out_eig_prefix, in_cool],
`black` ...

2021-09-02 15:51 UTC, sergpolly commented on tests/test_coverage.py
> +    assert cov[cov > 0].min() >= 1
the debate is still pending for this

2021-09-07 20:56 UTC, gfudenberg commented on cooltools/coverage.py
> -    covs = covs / 2
discussion 9/7/21:
-- lets go with removing /2 everywhere, including the [special case]( https://github.com/open2c/cooltools/blob/ff066aca1cd1569c119cfe74efdb54beee580e20/cooltools/coverage.py#L111), and update the docstring to clarify that the sum( total_coverage) from this function is 2x the number of reads contributing to the cooler. The storage mode is apparently for a different type of coolers (e.g. RNA vs DNA) that are not supported currently by cooltools.
    
Calculate the sums of cis and genome-wide contacts (aka coverage aka marginals) for  a sparse Hi-C contact map in Cooler HDF5 format. Note that the sum( `tot_raw_cov`) from this function is two times the number of reads contributing to the cooler as each side contributes to the coverage.

2021-09-08 14:19 UTC, sergpolly commented on tests/test_coverage.py
> +    assert cov[cov > 0].min() >= 1
Based on the discussion 9/7/2021 -> this is correct

2021-09-08 14:35 UTC, sergpolly approved these changes

2021-09-08 15:07 UTC, merged